version: '3'
services:
  preprocesor-testing:
    hostname: preprocesor-testing
    container_name: preprocesor-testing
    build:
      context: ../ctr/preprocessor_testing
      dockerfile: preprocessor-testing.Dockerfile
    user: root
    # environment:
    # env_file:
    #   - ./.env
    volumes:
       - "../source:/home/source" 
       - "../data:/home/data"        
    privileged: true
    tty: true
    
    # ports:
    #   - "8888:8888"
    # restart: unless-stopped
    # command: start.sh jupyter lab --NotebookApp.token=''
  # embulk:
  #   hostname: embulk
  #   build:    
  #     context: .
  #     dockerfile: embulk.Dockerfile
  #   user: root
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - "./embulk:/work/etl/embulk"
  #     - "./data:/work/etl/data"
  #   tty: true